In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("~/Desktop/code/sf-data-project/data/processed/human_animal_waste_311.csv")

In [4]:
df.head()

,CaseID,Opened,Closed,Updated,Status,StatusNotes,ResponsibleAgency,Category,RequestType,RequestDetails,...,:@computed_region_fcz8_est8,:@computed_region_pigm_ib2e,:@computed_region_9jxd_iqea,:@computed_region_6ezc_tdp2,:@computed_region_6pnf_4xz7,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_2dwj_jsy4,:@computed_region_y6ts_4iup,Neighborhoods
0,11872343,12/29/2019 09:52:00 AM,12/30/2019 04:10:00 PM,12/30/2019 04:10:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,3.0,NaN,NaN,NaN,2.0,NaN,3.0,NaN,NaN,53.0
1,11931510,01/11/2020 04:12:00 PM,01/13/2020 04:04:00 PM,01/13/2020 04:04:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,32.0
2,11872386,12/29/2019 10:06:00 AM,12/30/2019 07:56:00 PM,12/30/2019 07:56:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,22.0
3,11872557,12/29/2019 10:52:41 AM,12/30/2019 07:46:00 AM,12/30/2019 07:46:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,16.0
4,11872553,12/29/2019 10:51:53 AM,12/30/2019 09:50:00 AM,12/30/2019 09:50:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,18.0,7.0,1.0,2.0,1.0,NaN,NaN,NaN,32.0

In [5]:
pd.isnull(df).any()

CaseID                         False
Opened                         False
Closed                          True
Updated                        False
Status                         False
StatusNotes                     True
ResponsibleAgency              False
Category                       False
RequestType                    False
RequestDetails                  True
Address                        False
Street                          True
SupervisorDistrict              True
Neighborhood                    True
PoliceDistrict                  True
Latitude                       False
Longitude                      False
Point                          False
Source                         False
MediaURL                        True
SFFindNeighborhoods             True
CurrentPoliceDistricts          True
CurrentSupervisorDistricts      True
AnalysisNeighborhoods           True
:@computed_region_rxqg_mtj9     True
:@computed_region_yftq_j783     True
:@computed_region_jx4q_fizf     True
:@computed_region_bh8s_q3mv     True
:@computed_region_p5aj_wyqh     True
:@computed_region_fyvs_ahh9     True
:@computed_region_f58d_8dbm     True
:@computed_region_9dfj_4gjx     True
:@computed_region_vtsz_7cme     True
:@computed_region_n4xg_c4py     True
:@computed_region_sruu_94in     True
:@computed_region_4isq_27mq     True
:@computed_region_viu7_rrfi     True
:@computed_region_fcz8_est8     True
:@computed_region_pigm_ib2e     True
:@computed_region_9jxd_iqea     True
:@computed_region_6ezc_tdp2     True
:@computed_region_6pnf_4xz7     True
:@computed_region_h4ep_8xdi     True
:@computed_region_nqbw_i6c3     True
:@computed_region_2dwj_jsy4     True
:@computed_region_y6ts_4iup     True
Neighborhoods                   True
dtype: bool

In [6]:
t = pd.tslib.Timestamp.now()

AttributeError: module 'pandas' has no attribute 'tslib'

In [7]:
df['year'] = pd.DatetimeIndex(df['Opened']).year

In [8]:
df.head()

,CaseID,Opened,Closed,Updated,Status,StatusNotes,ResponsibleAgency,Category,RequestType,RequestDetails,...,:@computed_region_pigm_ib2e,:@computed_region_9jxd_iqea,:@computed_region_6ezc_tdp2,:@computed_region_6pnf_4xz7,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_2dwj_jsy4,:@computed_region_y6ts_4iup,Neighborhoods,year
0,11872343,12/29/2019 09:52:00 AM,12/30/2019 04:10:00 PM,12/30/2019 04:10:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,2.0,NaN,3.0,NaN,NaN,53.0,2019
1,11931510,01/11/2020 04:12:00 PM,01/13/2020 04:04:00 PM,01/13/2020 04:04:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,1.0,2.0,1.0,NaN,NaN,NaN,32.0,2020
2,11872386,12/29/2019 10:06:00 AM,12/30/2019 07:56:00 PM,12/30/2019 07:56:00 PM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,22.0,2019
3,11872557,12/29/2019 10:52:41 AM,12/30/2019 07:46:00 AM,12/30/2019 07:46:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,16.0,2019
4,11872553,12/29/2019 10:51:53 AM,12/30/2019 09:50:00 AM,12/30/2019 09:50:00 AM,Closed,Case Resolved,DPW Ops Queue,Street and Sidewalk Cleaning,Human or Animal Waste,Human or Animal Waste,...,18.0,7.0,1.0,2.0,1.0,NaN,NaN,NaN,32.0,2019

In [9]:
waste_by_years = df.groupby('year').count()

In [10]:
waste_by_years.sort_values('year').reset_index()

,year,CaseID,Opened,Closed,Updated,Status,StatusNotes,ResponsibleAgency,Category,RequestType,...,:@computed_region_fcz8_est8,:@computed_region_pigm_ib2e,:@computed_region_9jxd_iqea,:@computed_region_6ezc_tdp2,:@computed_region_6pnf_4xz7,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_2dwj_jsy4,:@computed_region_y6ts_4iup,Neighborhoods
0,2008,1746,1746,1746,1746,1746,1741,1746,1746,1746,...,697,602,575,500,1678,512,725,44,8,1673
1,2009,5771,5771,5771,5771,5771,5769,5771,5771,5771,...,2038,2784,2896,2721,5381,2728,2101,178,63,5367
2,2010,5852,5852,5852,5852,5852,5852,5852,5852,5852,...,2124,2991,3290,3068,5689,3084,2171,264,69,5675
3,2011,5693,5693,5690,5693,5693,5693,5693,5693,5693,...,2113,3010,3473,3298,5513,3320,2161,224,34,5511
4,2012,6403,6403,6396,6403,6403,6401,6403,6403,6403,...,2657,3480,3735,3637,6228,3655,2714,282,66,6225
5,2013,8880,8880,8870,8880,8880,8835,8880,8880,8880,...,3628,4649,5048,4967,8667,4982,3760,416,109,8652
6,2014,10693,10693,10679,10693,10693,10693,10693,10693,10693,...,4499,5570,6148,6260,10526,6270,4657,547,78,10494
7,2015,13387,13387,13383,13387,13387,13386,13387,13387,13387,...,5808,5233,4749,4743,13164,4760,6033,432,91,13145
8,2016,18573,18573,18439,18573,18573,18573,18573,18573,18573,...,7724,6560,5992,5960,18473,5989,8208,745,242,18445
9,2017,20945,20945,20655,20945,20945,20945,20945,20945,20945,...,7591,6188,5371,5018,20903,5050,8174,789,264,20894
10,2018,28354,28354,28125,28354,28354,28354,28354,28354,28354,...,10442,7698,6322,5628,28317,5670,11236,815,206,28294
11,2019,31002,31002,30597,31002,31002,31002,31002,31002,31002,...,10568,7621,6849,6272,30962,6332,11667,876,215,30941
12,2020,4523,4523,4352,4523,4523,4523,4523,4523,4523,...,1491,1053,1187,1174,4517,1186,1652,70,14,4517

In [ ]:
df.plot(kind='scatter', x='year', y='Opened')

In [ ]:
by_years= waste_by_years.sort_values('year').reset_index()